### PR TITLE
Added a new class

### PR DESCRIPTION
**Pull request by calculatorkittycat**
A new class with code to find a prime number. this is a test for adding a pull request from intelli j

### CODE REVIEW

**Review by AbrahamWang484 — APPROVED** [review]
cool code! good to go!

**Comment by olegiakim** [comment]
Awesome!

**Review by AbrahamWang484 — APPROVED** [review]
good

**Review by ABChaos8 — APPROVED** [review]
cool code

**Review by Nasratullahsarabi — APPROVED** [review]
Good

**Review by Nasratullahsarabi — APPROVED** [review]
Good codes

**Pull request merged**
