### PR TITLE
Please approve my hello.class

### PR DESCRIPTION
**Pull request by AbrahamWang484**

### CODE REVIEW

**Review by ozStark — APPROVED** [review]
Good morning!

**Review by calculatorkittycat — APPROVED** [review]
Wow I can approve from intelli J too! atleast it appears that way

**Review by ozStark — APPROVED** [review]
This is cool!

**Comment by Nasratullahsarabi** [comment]
Great

**Review by Nasratullahsarabi — APPROVED** [review]

**Comment by olegiakim** [comment]
Awesome!

**Pull request merged**
