### PR TITLE
Ivan push 1

### PR DESCRIPTION
**Pull request by calculatorkittycat**
This is my first push for Javengers2.0

### CODE REVIEW

**Review by AbrahamWang484 — APPROVED** [review]

**Review by olegiakim — APPROVED** [review]
Great!

**Review by ozStark — APPROVED** [review]
done

**Comment by Nasratullahsarabi** [comment]
Looks cool

**Review by davutdogan — APPROVED** [review]
good work

**Review by Nasratullahsarabi — APPROVED** [review]
Looks nice

**Pull request merged**
